DEFAULT_URLS = ["https://callowayatlascolinas.com/floorplans/",
    "https://rent.brookfieldproperties.com/floorplans/?nab=1&propertyId[]=1807793",
    "https://www.rainymeadows.com/floorplans/#location",
    "https://www.casaazultownhomes.com/floorplans/#location",
    "https://meravintagepark.com/floorplans/",
    "https://www.ivypointcypress.com/floorplans/#location",
    "https://www.discoveryatwestroad.com/floorplans/#location",
    "https://www.missionhill-apartments.com/interactive-site-map",
    "https://soleacopperfield.com/floorplans/",
    "https://www.camdenliving.com/apartments/leander-tx/camden-leander/available-apartments",
    "https://www.thepattenwest.com/floor-plans",
    "https://berkshirecreekside.com/floorplans/",
    "https://monarchexchangespring.com/floorplans/",
    "https://foxwoodaustin.com/floorplans/",
    "https://www.windsorcommunities.com/properties/legacy-at-windsor/floorplans/?spaces_tab=map",
    "https://www.heritageatlakeside.com/plano/heritage-at-lakeside/conventional/",
    "https://www.agorastoneoak.com/Floor-plans.aspx",
    "https://www.irtliving.com/Apartments-In/San-Antonio-TX/Los-Robles",
    "https://www.steeplewaydowns.com/houston/steepleway-downs/conventional/",
    "https://www.discoveryatmandolin.com/interactive-map",
    "https://www.senderoridge.com/floor-plans",
    "https://www.liveatthegriffin.com/interactive-leasing",
    "https://www.raveneauxapts.com/houston/raveneaux/conventional/",
    "https://gardensatgreenhouse.com/floorplans/",
    "https://www.irtliving.com/Apartments-In/Tampa-FL/Vantage-On-Hillsborough",
    "https://www.helixatmedcenter.com/houston/helix-at-med-center/conventional/",
    "https://www.olympusatwatersideestates.com/floor-plans",
    "https://www.vecinaapts.com/san-antonio/vecina-mt/conventional/",
    "https://sawmillvillageapts.com/floorplans/",
    "https://www.akelius-properties.us/leander-park/floorplans",
    "https://www.liveatgreenhouseapartments.com/houston-tx-apartments/greenhouse/conventional/",
    "https://harlowspringcypress.com/floorplans/",
    "https://villasatlegacy-plano.com/floorplans/",
    "https://amiraatwestly.com/floorplans/",
    "https://districtatmemorial.com/floorplans/",
    "https://lakeshorevillas-apts.com/floorplans/",
    "https://www.pinesofwoodforest.com/houston/pines-of-woodforest/conventional/",
    "https://www.audubonvillagetampa.com/floorplans/#location",
    "https://somersetapthomes.com/floorplans/",
    "https://www.springsapartments.com/apartments/tx/rosenberg/springs-at-summer-park/floor-plans",
    "https://www.brazosranch-apts.com/rosenberg/brazos-ranch/conventional/",
    "https://broadstonetoscano.com/floorplans/?arbitrary_1=1",
    "https://elanmedcenter.com/floorplans/",
    "https://www.mezzomedcenter.com/Floor-plans.aspx?oll_ilm=obl&oll_utm_source=gmb&oll_utm_medium=organic",
    "https://adenineapartments.com/floorplans/",
    "https://cortland.com/apartments/cortland-north-haven/available-apartments/",
    "https://www.thearborsofeulessapartments.com/apartments/tx/euless/floor-plans#/",
    "https://www.devonnorthgate.com/irving/devon-on-northgate/conventional/",
    "https://www.broadstoneonmedical.com/floorplans?utm_source=gmb&utm_medium=organic&oll_rccustomid=Mzg0NDk%3D-Bt0i93uucs0%3D&oll_utm_source=gmb&oll_utm_medium=organic",
    "https://www.mallardcreekkingwood.com/floorplans/#location",
    "https://www.towncentercrossingapts.com/kingwood/town-center-crossing/conventional/?oll_switch_cls%5Bid%5D=64893&switch_cls%5Bid%5D=64893&oll_utm_source=gmb&oll_utm_medium=organic",
    "https://signatureridgeliving.com/floorplans/",
    "https://thejaxapts.com/floorplans/",
    "https://www.prestonpeakapartments.com/floorplans?utm_source=gmb&utm_medium=organic&oll_utm_source=gmb&oll_utm_medium=organic",
    "https://www.morgan-properties.com/apartments/oh/fairfield/cobblestone-grove/check-availability#/",
    "https://www.udr.com/dallas-apartments/addison/addison-apartments-at-the-park/apartments-pricing/interactive/#/?layers=0,1&beds=1,2,3,0",
    "https://www.olympusauburnlakes.com/floor-plans",
    "https://www.encoreonthebay.com/floorplans/#location",
    "https://www.liveatshoronclearlake.com/floorplans/#availabilities/",
    "https://www.liveatvillasbythebay.com/floorplans/#availabilities/",
    "https://www.udr.com/dallas-apartments/farmers-branch/the-canal/apartments-pricing/interactive/#/?layers=0,1&beds=1,2",
    "https://www.falltreeapts.com/floorplans/",
    "https://www.onetownecrestapts.com/floorplans/#location",
    "https://www.irtliving.com/Apartments-In/Cypress-TX/Carrington-Park-at-Huffmeister?switch_cls%5Bid%5D=101750&utm_source=google&utm_medium=organic&utm_campaign=carringtonparkathuffmeister&utm_content=gmb-listing",
    "https://tuscanlakesapt.com/floorplans/",
    "https://cortland.com/apartments/cortland-fossil-creek/available-apartments/",
    "https://www.villasatcypresswood.net/houston/villas-at-cypresswood/conventional/",
    "https://www.oaksproperties.com/apartments/tx/las-colinas/hackberry-creek/floor-plans#/floorplans/1990823257/",
    "https://www.blairatbitters.com/floorplans/#location",
    "https://palmerlascolinas.com/floorplans/",
    "https://verandaatcenterfield.com/floorplans/",
    "https://www.trailwoodvillageliving.com/kingwood/trailwood-village-apartments/conventional/"
]


PROPERTY_NAMES = {
    "rent.brookfieldproperties.com": "The Arbors of Las Colinas",
    "callowayatlascolinas.com": "Calloway at Las Colinas",
    "casaazultownhomes.com": "casaazul Townhomes",
    "rainymeadows.com": "Rainy meadows",
    "meravintagepark.com": "Mera Vintage Park",
    "discoveryatwestroad.com": "Discovery AT WEST ROAD",
    "ivypointcypress.com": "IVY POINT Cypress",
    "missionhill-apartments.com": "MISSION HILL APARTMENTS",
    "camdenliving.com": "CAMDEN, LEANDER",
    "thepattenwest.com": "THE PATTEN WEST",
    "soleacopperfield.com": "SOLEA COPPERFIELD",
    "monarchexchangespring.com": "MONARCH EXCHANGE",
    "foxwoodaustin.com": "Foxwood, Austin",
    "berkshirecreekside.com": "BERKSHIRE CREEKSIDE",
    "heritageatlakeside.com": "HERITAGE AT LAKESIDE",
    "agorastoneoak.com": "AGORA STONE OAK",
    "steeplewaydowns.com": "STEEPLEWAY DOWNS APARTMENT",
    "windsorcommunities.com": "WINDSOR",
    "discoveryatmandolin.com": "DISCOVERY AT MANDOLIN",
    "liveatthegriffin.com": "THE GRIFFIN",
    "irtliving.com/Apartments-In/San-Antonio-TX/Los-Robles": "LOS ROBLES",
    "irtliving.com/Apartments-In/Tampa-FL/Vantage": "VANTAGE ON HILLSBOROUGH",
    "irtliving.com/Apartments-In/Cypress-TX/Carrington": "CARRINGTON PARK AT HUFFMEISTER",
    "raveneauxapts.com": "Raveneaux Apartments",
    "helixatmedcenter.com": "HELIX AT MED CENTER",
    "senderoridge.com": "SENDERO RIDGE",
    "vecinaapts.com": "VECINA",
    "sawmillvillageapts.com": "SAW MILL VILLAGE",
    "gardensatgreenhouse.com": "THE GARDENS AT GREENHOUSE",
    "liveatgreenhouseapartments.com": "GREENHOUSE APARTMENTS",
    "harlowspringcypress.com": "HARLOW SPRING CYPRESS",
    "olympusproperty.com/apartments/tx/richmond": "OLYMPUS AT WATERSIDE ESTATES",
    "olympusproperty.com/apartments/tx/spring": "OLYMPUS AUBURN LAKES",
    "amiraatwestly.com": "AMIRA AT WESTLY",
    "districtatmemorial.com": "DISTRICT AT MEMORIAL",
    "akelius-properties.us": "LEANDER PARK",
    "pinesofwoodforest.com": "PINES OF WOODFOREST",
    "audubonvillagetampa.com": "AUDUBON VILLAGE, TAMPA",
    "somersetapthomes.com": "SOMERSET APARTMENT HOMES",
    "springsapartments.com": "SPRINGS AT SUMMER PARK",
    "villasatlegacy-plano.com": "VILLAS AT LEGACY",
    "lakeshorevillas-apts.com": "LAKESHORE VILLAS",
    "broadstonetoscano.com": "BROADSTONE TOSCANO",
    "elanmedcenter.com": "ELAN MED CENTER",
    "adenineapartments.com": "ADENINE APARTMENT HOMES",
    "brazosranch-apts.com": "BRAZOS RANCH APARTMENT HOMES",
    "thearborsofeulessapartments.com": "THE ARBORS",
    "devonnorthgate.com": "DEVON NORTHGATE",
    "mezzomedcenter.com": "MEZZO KIRBY MED CENTER",
    "broadstoneonmedical.com": "BROADSTONE ON MEDICAL",
    "mallardcreekkingwood.com": "MALLARD CREEK",
    "cortland.com/apartments/cortland-north-haven": "CORTLAND NORTH HAVEN",
    "cortland.com/apartments/cortland-fossil-creek": "CORTLAND FOSSIL CREEK",
    "signatureridgeliving.com": "SIGNATURE RIDGE",
    "thejaxapts.com": "THE JAX",
    "morgan-properties.com": "COBBLESTONE GROVE",
    "towncentercrossingapts.com": "TOWN CENTER CROSSING",
    "encoreonthebay.com": "ENCORE ON THE BAY",
    "udr.com/dallas-apartments/addison": "ADDISON APARTMENTS AT THE PARK",
    "udr.com/dallas-apartments/farmers-branch": "THE CANAL",
    "prestonpeakapartments.com": "PRESTON PEAK",
    "liveatshoronclearlake.com": "SHOR ON CLEAR LAKE",
    "falltreeapts.com": "FALL TREE APARTMENTS",
    "liveatvillasbythebay.com": "VILLAS BY THE BAY",
    "villasatcypresswood.net": "VILLAS AT CYPRESSWOOD",
    "tuscanlakesapt.com": "GRAND VILLAS AT TUSCAN LAKES",
    "onetownecrestapts.com": "ONE TOWNECREST APARTMENTS",
    "oaksproperties.com": "OAKS HACKBERRY CREEK",
    "myaltamonte.com": "ALTAMONTE",
    "theayvaapts.com": "THE AYVA",
    "blairatbitters.com": "BLAIR AT BITTERS",
    "palmerlascolinas.com": "PALMER LAS COLINAS",
    "verandaatcenterfield.com": "VERANDA AT CENTERFIELD",
    "www.trailwoodvillageliving.com": "TRAILWOOD VILLAGE APARTMENTS"
}
